pshift_genpc:
  camera:
    ExposureTime: 8400
    Gain: 0
  projector:
    ExposureTime: 20
    Intencity: 120
    Interval: 40
    Mode: 1
  paramset:
    camera:
      ExposureTime: [8400,8400,8400,16800,16800]
      Gain: [0,0,0,0,0]
    projector:
      Intencity: [40,120,255,100,255]
      Interval: [40,40,40,60,60]
live:
  camera:
    AcquisitionFrameRate: 30
    GainAnalog: 3
    ExposureTime: 30000
    Gain: 50
    SoftwareTriggerRate: 4
  paramset:
    camera:
      ExposureTime: [3000,5000,10000,20000,30000]
      Gain: [0,0,0,0,63]

