config:
  searcher:
    solver: ransac_solver
    scenes: ["surface"]
    scene_frame_ids: ["camera/capure0"]
    master_frame_ids: ["camera/master0"]
    base_frame_id: "world"
    solve_frame_id: "camera/capture0"
  picker:
    multiplex: 1
    solve_frame_id: "camera/capture0"
